//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionForGIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverForFine
    {
        public int Id_DriverFine { get; set; }
        public Nullable<int> Id_Fine { get; set; }
        public Nullable<int> Id_Driver { get; set; }
    }
}
