//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionForGIBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterCar
    {
        public int Id { get; set; }
        public string PassportDriver { get; set; }
        public string PassportVehicle { get; set; }
        public string InsuranceCar { get; set; }
        public string NumberPhone { get; set; }
    }
}
